name: Build torproxy Image

on:
  workflow_dispatch:

  schedule:
  - cron: '0 10 12 * *' # once a month at 10:00 on the 12th, an odd choice to avoid peak times

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/torproxy

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - id: lowercase-repo
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          provenance: false
          platforms: "linux/arm64,linux/amd64"
          push: true
          tags: ${{ env.REGISTRY }}/${{ steps.lowercase-repo.outputs.lowercase }}:latest
